<a href="https://colab.research.google.com/github/YJ0317/data-science-toolkit/blob/main/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 Array:\n", array_2x2)


2x2 Array:
 [[1 2]
 [3 4]]


In [7]:
random_3x4 = np.random.rand(3, 4)
print("\n Random 3x4 Array:\n", random_3x4)


 Random 3x4 Array:
 [[0.18187231 0.35589445 0.86364538 0.39665614]
 [0.85621778 0.26138361 0.14434415 0.38784931]
 [0.46668886 0.46952784 0.714774   0.9776381 ]]


In [9]:
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))
print("\n Array of Ones:\n", ones_array)
print("\n Array of Zeros:\n", zeros_array)


 Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

 Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
random_6x3 = np.random.rand(6, 3)
transposed = random_6x3.T
print("\n Random 6x3 Array:\n", random_6x3)
print("\n Transposed (3x6):\n", transposed)


 Random 6x3 Array:
 [[0.0303521  0.98759257 0.05350843]
 [0.89560256 0.93919898 0.49350382]
 [0.72377795 0.13670329 0.34171644]
 [0.71216652 0.51825786 0.5388543 ]
 [0.37249592 0.30358867 0.31628703]
 [0.39565622 0.72314667 0.29577052]]

 Transposed (3x6):
 [[0.0303521  0.89560256 0.72377795 0.71216652 0.37249592 0.39565622]
 [0.98759257 0.93919898 0.13670329 0.51825786 0.30358867 0.72314667]
 [0.05350843 0.49350382 0.34171644 0.5388543  0.31628703 0.29577052]]


In [11]:
n, p, m = 3, 2, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)
print("\n Matrix A (3x2):\n", A)
print("\n Matrix B (2x4):\n", B)
print("\n Dot Product (3x4):\n", dot_product)


 Matrix A (3x2):
 [[0.39488321 0.41736458]
 [0.81095614 0.65099317]
 [0.48752842 0.29178558]]

 Matrix B (2x4):
 [[0.09815301 0.48266673 0.58415368 0.32428408]
 [0.1416232  0.04890835 0.58516036 0.56024886]]

 Dot Product (3x4):
 [[0.09786749 0.2110096  0.47489769 0.36188237]
 [0.17179353 0.42326055 0.85465841 0.62769834]
 [0.08917599 0.2495845  0.45553288 0.32157024]]
